name: Terraform Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  segredos: ${{ secrets.segredos }}


jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: teste
        run: echo "segredos: ${{ env.segredos }}"
