name: "PROD DEPLOY"

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    uses: ./.github/workflows/develop.yml
    with:
      environment: prod
      aws-assume-role-arn: "arn:aws:iam::767263037932:role/github-actions-Wilson-Salomao733-pipeline"
      aws-region: "us-east-2"
      aws-statefile-s3-bucket: "wilson-salomao733-us-east-2-terraform-statefile"
      aws-lock-dynamodb-table: "wilson-salomao733-us-east-2-terraform-lock"