name: Hello World Terraform Plan

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest

    environment: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Terraform Init
        run: |
            cd infra/envs && terraform init
 
      - name: Terraform Validate
        run: |
            cd infra/envs && terraform validate
 
      - name: Terraform Plan
        run: |
            cd infra/envs && terraform plan

      - name: Terraform Apply
        run: |
            cd infra/envs && terraform apply
